name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Este pipeline se ejecutará cuando haya un push a la rama principal
  pull_request:
    branches:
      - main  # También se ejecutará cuando se cree un pull request a la rama principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Check out del código del repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Puedes elegir la versión de Node.js que uses en tu app

      # Paso 3: Instalar las dependencias
      - name: Install dependencies
        run: npm install

      # Paso 4: Ejecutar pruebas (si tienes pruebas)
      - name: Run tests
        run: npm test  # O cualquier comando que utilices para tus pruebas

      # Paso 5: Construir la aplicación (para aplicaciones React por ejemplo)
      - name: Build app
        run: npm run build

      # Paso 6: Configurar el acceso a la máquina virtual en AWS
      - name: Set up SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Paso 7: Desplegar a la máquina virtual de AWS (usando SSH)
      - name: Deploy to AWS EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@<IP-de-tu-VM> << 'EOF'
            cd /ruta/a/tu/app
            git pull origin main  # O el comando que uses para obtener los últimos cambios
            npm install  # Instala las dependencias en la VM
            pm2 restart server.js  # O el comando que uses para reiniciar tu aplicación
          EOF
