name: Deploy to AWS EC2 with NGINX

on:
  push:
    branches:
      - main  # Despliega cuando haya un push a la rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "DB_HOST=localhost" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_PORT=3306" >> .env


      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Connect to AWS VM
        run: ssh -i ~/.ssh/id_rsa ec2-user@3.144.108.21 "echo 'Connected successfully!'"

      - name: Deploy to AWS EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.AWS_VM_IP }} << "EOF"
            cd /ruta/a/tu/app
            git pull origin main
            npm install
            pm2 restart server.js  # O el comando para reiniciar tu app, dependiendo de cómo la administres
            # sudo systemctl restart nginx  # Reinicia NGINX para asegurarte de que la configuración está actualizada
          EOF
